on:
  schedule:
    - cron: "0/5 * * * *"
    - cron: "0/6 * * * *"
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls -a
      - name: checkout
        uses: actions/checkout@v1
      - name: after checkout list files
        run: |
          ls -a
          pwd
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"

